[project]
name = "stock-mcp"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.11.2",
    "httpx>=0.24.0",
    "pydantic>=2.11.7",
    "scipy>=1.16.1",
    "yfinance>=0.2.65",
]
